### ISSUE TITLE
Whitescreen

### ISSUE THREAD

**Issue by protoknight12** [TodePond/Arroost#1]
When I download arrowpond and run it by the index.html it displays a whitescreen and nothing else

**Comment by TodePond** [comment]
That's because I haven't made it yet :)

**Comment by protoknight12** [comment]
Wha-

**Comment by TodePond** [comment]
Yes this is something I'm making for 3 or 4 videos away. (Not the next video, or the one after that, or the one after that, but maybe the one after that)!

**Comment by Magnogen** [comment]
Is it the next video now?

**Comment by TodePond** [comment]
yes!

**Comment by Magnogen** [comment]
Wahoo!! 🎉 💃 🎉

**Comment by TodePond** [comment]
not a white screen anymore https://incandescent-kitten-32f1ef.netlify.app/
