### ISSUE TITLE
Test it on windows

### ISSUE THREAD

**Issue by TodePond** [TodePond/Arroost#103]
What are the current issues on windows?

**Comment by jessiejs** [comment]
I'm willing to test, if I knew how the heck to use this thing, what i've figured out is that you can press the big orb and a small orb comes out, if you right click ten small orbs spawn, and eventually a plus thing will spawn, and there's a number next to your cursor displaying the amount of orbs, I haven't figured out what the line when you click on the plus does yet.

**Comment by TodePond** [comment]
Sounds good to me! Thanks for testing :)

I should write up some qa testing guides

**Comment by TodePond** [comment]
I added an issue for it: #106
