### ISSUE TITLE
Add shadow around circles

### ISSUE THREAD

**Issue by jessiejs** [TodePond/Arroost#108]
Personally I think right now when you have two circles intersecting it just looks a little bit bad and muddy, so my idea is to add box shadows, in CSS it would look like

```css
box-shadow: 0px 4px 8px 0px rgba(0, 0, 0, 0.25), 0px 0px 4px 0px rgba(0, 0, 0, 0.15);
```

![An image of three circles on the left, intersecting, hard to tell apart, and the same three circles on the right, but with shadows to make things clearer](https://github.com/TodePond/Arroost/assets/63984309/706a4484-ce27-4037-9db4-54f63dbbe560)

I would like to take a shot at doing it myself later, but I'm still trying to figure out the codebase.

**Comment by TodePond** [comment]
Dang these look really nice!!!! Love the border too.

The arroost section of the codebase is slightly unusual, but it's basically an entity component system.

The best way of adding this is probably adding a `shadow` property to the Style component (probably a boolean to start with): https://github.com/TodePond/Arroost/blob/main/source/arroost/components/style.js

And then setting that property to true in for the cells. I have a helper that applies some shared styles to all 'cells' (which are the circles). It's called `setCellStyles`: https://github.com/TodePond/Arroost/blob/main/source/arroost/entities/cells/util.js

We call it in `dummy.js`, `dummy-creation.js`, and `creation.js`. And I'll call it in all future cells too.

**Comment by TodePond** [comment]
If you have any questions about the codebase let me know! :)

**Comment by jessiejs** [comment]
Created PR #109
https://deploy-preview-109--kaleidoscopic-rabanadas-4ce9da.netlify.app/
