### ISSUE TITLE
Add arrow flaps to Dummy of Time

### ISSUE THREAD

**Issue by TodePond** [TodePond/Arroost#143]
Add visual arrow flaps in the middle to show its direction

**Comment by loglot** [comment]
this new "dummy of time" makes this a good 3d modeling software!
![image](https://github.com/TodePond/Arroost/assets/88983354/35dc29b2-cea0-45e1-bbb5-17cfffde2828)

**Comment by TodePond** [comment]
Ahhh love it !

**Comment by loglot** [comment]
accidentally deleted it
here it is again
![image](https://github.com/TodePond/Arroost/assets/88983354/680eec50-ec5d-4914-8ad2-d3d8709b2079)
