### ISSUE TITLE
loops with the dummy of Connection

### ISSUE THREAD

**Issue by loglot** [TodePond/Arroost#148]
i feel like when you make a loop with the dummy of Connection, that loop should just stay on.

**Comment by TodePond** [comment]
You'll be able to make loops by making a wire 'delayed'. every pulse ends when the beat advances :)

**Comment by loglot** [comment]
alright! just gotta wait for that ability, also what is the dummy of time, and how to I access it (if there even is a way)

**Comment by TodePond** [comment]
the dummy of time is the line that's there when two cells are connected together. it's called 'dummy of time' because it's like a simpler version of the 'arrow of time', which I'm still working on as part of #31

**Comment by loglot** [comment]
Oh! Ok!
