### ISSUE TITLE
connection not unlockable

### ISSUE THREAD

**Issue by mahdiyadiilavi1** [TodePond/Arroost#185]
no sign of unlocking it in code

**Comment by mahdiyadiilavi1** [comment]
in "the" code. sorry for bad typo

**Comment by loglot** [comment]
Press "c"

**Comment by TodePond** [comment]
It was bugged! @mahdiyadiilavi1 fixed it in #184

**Comment by loglot** [comment]
It worked for me lol

**Comment by TodePond** [comment]
pressing "c" works but the normal way to unlock it didn't

**Comment by loglot** [comment]
Oh, I just pressed random buttons on my keyboard until it worked lol
