### ISSUE TITLE
Cannot click cells in mobile (record sound or fire)

### ISSUE THREAD

**Issue by mahdoosh1** [TodePond/Arroost#217]
This was possble previously. But not now

**Comment by TodePond** [comment]
Hey, what browser and operating system are you using?

**Comment by mahdoosh1** [comment]
OS: Android 13 Samsung Galaxy A12
Browser: Chrome (updated) version isnt required right?

**Comment by TodePond** [comment]
Thanks! That's weird, it's working for me on android chrome 🤔

**Comment by mahdoosh1** [comment]
Wait, now it is working but it lags for half a second and then fires

**Comment by TodePond** [comment]
hmm i wonder if it's something to do with it not registering the pointer events properly

**Comment by TodePond** [comment]
Oh wait! This is because it just waits until the next beat to fire. This is intended :)

**Comment by mahdoosh1** [comment]
but entire engine freezes, please fix
