### ISSUE TITLE
Handle multple clicks in mobile

### ISSUE THREAD

**Issue by mahdoosh1** [TodePond/Arroost#252]
Handle multple hand touches, basically a right click to pan while inaction(moving/connecting) feature for mobile.

Im not sure if this is already implemented for right click or not. But original issue is not closed.

I know, this is hard, if you think this can't be done quick enough, you can add Strech goal label.

**Comment by mahdoosh1** [comment]
#94

**Comment by TodePond** [comment]
https://github.com/TodePond/Arroost/issues/65
