### ISSUE TITLE
Wrong fire Color

### ISSUE THREAD

**Issue by mahdoosh1** [TodePond/Arroost#267]
![Screenshot_20231204-204017-1.jpg](https://github.com/TodePond/Arroost/assets/83725163/bb00ce23-8ba2-44bc-89b9-5ad34f586512)

**Comment by mahdoosh1** [comment]
Arrow of Time should not be Green

**Comment by mahdoosh1** [comment]
Wait, Im stupid. Sorry

**Comment by BestGiter** [comment]
you arent stupid, its just that when color goes through white, it stays as same color
