### ISSUE TITLE
unable to do anything after using wire tool on the square color changers

### ISSUE THREAD

**Issue by Jeremy5909** [TodePond/Arroost#269]

**Comment by TodePond** [comment]
I can't reproduce this. Can you write out some reproduction steps, or take a video?

**Comment by Jeremy5909** [comment]
hmm its not doing it now for me. my browser mightve been bugging or smtn

**Comment by Jeremy5909** [comment]
I said color changer thing but i meant the arrow part/delay changer. It appears to do this half the time. I will try to find a more stable way of producing this

**Comment by mahdoosh1** [comment]
I dont understand what you said.

Do you mean you stuck when connecting smth to arrow of time? (The thing in middle of wire)

**Comment by mahdoosh1** [comment]
By Wire tool do you mean Arrow of connectin?

**Comment by Jeremy5909** [comment]
Yes and yes
