### ISSUE TITLE
🎵 Arrows in Arrows in Arrows

### ISSUE THREAD

**Issue by TodePond** [TodePond/Arroost#3]
## Preparation
- [x] Tree of Fame
- [x] Habitat
- [x] Cursors
- [x] Screen of Fame

## Script
- [x] Intro
- [x] Arrow of Creation
- [x] Arrow of Recording
- [x] Arrow of Noise
- [x] ---
- [x] Arrow of Connection
- [x] Arrow of Time
- [x] Arrow of Timing
- [x] ---
- [x] Arrow of Colour
- [x] Arrow of Definition
- [x] ---
- [x] Arrow of Infinity
- [x] Outro

## Voice
- [x] Intro
- [x] Arrow of Creation
- [x] Arrow of Recording
- [x] Arrow of Noise
- [x] ---
- [x] Arrow of Connection
- [x] Arrow of Time
- [x] Arrow of Timing
- [x] ---
- [x] Arrow of Colour
- [x] Arrow of Definition
- [x] ---
- [x] Arrow of Infinity
- [x] Outro

## Code
- [x] Intro
- [x] Arrow of Creation
- [x] Arrow of Recording
- [x] Arrow of Noise
- [x] ---
- [x] Arrow of Connection
- [x] Arrow of Time
- [x] Arrow of Timing
- [x] ---
- [x] Arrow of Colour
- [x] Arrow of Definition
- [x] ---
- [x] Arrow of Infinity
- [x] Outro

## Music
- [x] Intro
- [x] Arrow of Creation
- [x] Arrow of Recording
- [x] Arrow of Noise
- [x] ---
- [x] Arrow of Connection
- [x] Arrow of Time
- [x] Arrow of Timing
- [x] ---
- [x] Arrow of Colour
- [x] Arrow of Definition
- [x] ---
- [x] Arrow of Infinity
- [x] Outro

## Video
- [x] Intro
- [x] Arrow of Creation
- [x] Arrow of Recording
- [x] Arrow of Noise
- [x] ---
- [x] Arrow of Connection
- [x] Arrow of Time
- [x] Arrow of Timing
- [x] ---
- [x] Arrow of Colour
- [x] Arrow of Definition
- [x] ---
- [x] Arrow of Infinity
- [x] Outro

## Outreach
- [x] Teaser 1
- [x] Teaser 2
- [ ] Ribbit report

**Comment by TodePond** [comment]
Tree of Fame time

**Comment by TodePond** [comment]
Tree of Fame done

Habitat time!!

**Comment by TodePond** [comment]
Working on some state management stuff for habitat, and did a cleanup

**Comment by TodePond** [comment]
Renamed ArrowRoost to Arroost

**Comment by TodePond** [comment]
I got some barebones structure going

and deployed at https://incandescent-kitten-32f1ef.netlify.app/

**Comment by TodePond** [comment]
I did some more updates to habitat

**Comment by TodePond** [comment]
I added a todo list of things to R+D

**Comment by TodePond** [comment]
Figured out all the arrows - now changed to list of things to code. Here we go!

**Comment by TodePond** [comment]
just a lil update: Arrow of Creation is going

Now working on Recording + Noise

**Comment by TodePond** [comment]
Moved em to issues

**Comment by TodePond** [comment]
Script done

**Comment by TodePond** [comment]
Technically, recording + noise code are done.
Creation still needs cloning!

**Comment by TodePond** [comment]
Voice done and edited - but will probably do some reshoots

**Comment by TodePond** [comment]
Update:

* I did a re-script and re-take and re-structure. It's good now! I should update the todo list accordingly. I think I could potentially drop the Arrow of Control but let's see how we go! eg: Could move pitch controls to the Arrow of Recording instead. Depends if I really need volume/lowpass/etc or not. If I do need it, I need the Arrow of Control.
* Teaser trailer is done, and out!
* I'm currently working on getting nogan + arroost to work together well.

**Comment by skifli** [comment]
You should really lock these issues to contributors only.

**Comment by TodePond** [comment]
no its ok :)

**Comment by TodePond** [comment]
Arroost and Nogan now WORKING TOGETHER

**Comment by TodePond** [comment]
Major progress on arroost UI, speeding up a lot now

**Comment by TodePond** [comment]
Updated to reflect current status

**Comment by TodePond** [comment]
yeah its gonna do some more stuff too :)

**Comment by TodePond** [comment]
arrow of reality code done

**Comment by TodePond** [comment]
updated script

**Comment by ivanreese** [comment]
No music!!!?

**Comment by mahdoosh1** [comment]
hey Luke, where did you learn js? in school or online course or where?

i am not good at js and i want to learn it properly, i have learned python using SoloLearn (not to advertise) are there any better choices?

**Comment by TodePond** [comment]
> hey Luke, where did you learn js? in school or online course or where?

I first learned javascript on codecademy! it was quite nice and simple back then though

**Comment by TodePond** [comment]
creation video done

**Comment by mahdoosh1** [comment]
> creation video done, also cursors and screen of fame done

Amazing!

Can't wait for the finished Video!!

**Comment by TodePond** [comment]
arrow of recording video done

**Comment by TodePond** [comment]
arrow of noise video done

**Comment by TodePond** [comment]
notes:

- title sequence misaligned background
- flip the panning of some things
- slower noise manipulation - add extra left and right if needed
- fewer 'berds'

**Comment by TodePond** [comment]
feedback applied, except for panning, which I'll do when I'm using my better headphones

**Comment by TodePond** [comment]
connection video done

**Comment by TodePond** [comment]
voice for time done

**Comment by TodePond** [comment]
video for timing done

**Comment by TodePond** [comment]
timing voice done

**Comment by TodePond** [comment]
first half of timing video done

**Comment by TodePond** [comment]
wrapping up for today, did most of the music for timing video. maybe add some wind instruments tomorrow

**Comment by TodePond** [comment]
notes:

- [ ] maybe tweak down the volume of second voice?
- [ ] tweak down volume of some later sounds?
- [ ] maybe a build-up sound to the "chain sounds" section
- [ ] maybe "chain sounds" could be low-passed? maybe not tho
- [ ] consider showing berd at "chain sounds". maybe too soon since the last time though. and blank screen is kinda cool.

**Comment by TodePond** [comment]
feedback applied
except for the "chain sounds" ones because gonna do more with that section anyway

**Comment by TodePond** [comment]
music for timing done

**Comment by TodePond** [comment]
CUT DESTRUCTION AND REALITY! don't need em

**Comment by TodePond** [comment]
TIMING VIDEO DONE

**Comment by TodePond** [comment]
readjusted todo list now that i cut some stuff

**Comment by TodePond** [comment]
ALL VOICE DONE.
and kept in a short version of definition

**Comment by TodePond** [comment]
outro music done

**Comment by TodePond** [comment]
mapped out infinity til end. need to record some voice for outro. but unsure how long itll be? hmm

**Comment by TodePond** [comment]
feedback

- [ ] i think it would be good to bring back in nara in the credits. feels like it deserves a proper ending
- [ ] xylophone too loud on non-bassy speakers
- [ ] go on, do the "NEW VIDEO EVERY" dripfeed

**Comment by mahdoosh1** [comment]
2 days until finished video! i guess..

**Comment by TodePond** [comment]
> 2 days until finished video! i guess..

my current guess is the 12th january

**Comment by TodePond** [comment]
OK re-toned the ending. much better now

**Comment by TodePond** [comment]
feedback all applied

**Comment by TodePond** [comment]
ARROW OF INFINITY CODE DONE also

maybe could make it show pulses? or just avoid that.
just avoid i think, its already pretty impressive

**Comment by TodePond** [comment]
ALL MUSIC DONE

video from here til the end

**Comment by TodePond** [comment]
all clips mapped out for the remainder of the video

**Comment by TodePond** [comment]
made the dream music more intentional

**Comment by TodePond** [comment]
- [ ] greatly simplify sounds in dream
- [ ] remove otomatone from outro

**Comment by TodePond** [comment]
- [ ] add (at least) 2 more berd t-shirts in build up to dream. more madness. consider little whistle in those bits to foreshadow? one of these clips can replace the empty tree. the other can either replace some arroost, or just get squeezed in. (see next point)
- [ ] ditch some arroost clips leading up to dream. let the boy shine.
- [ ] deal with the accidental whistle in the outro. it's the by accident but it kinda works!?!? or maybe not i dunno
- [ ] extend credits?? feels rushed.
- [ ] double check that none of the audio poops the speakers

**Comment by TodePond** [comment]
- [ ] remove white from spin down (and elsewhere). save white for after dream.
- [ ] give money shot white background
- [ ] clips jump too fast just before dream. i told u - more berd roll, less b roll.

**Comment by TodePond** [comment]
- [ ] pout slightly out of time
- [ ] at the very least, try out fading to white at end
- [ ] in the pre-dream, start doing the black 'pauses' perhaps (to start with)

**Comment by TodePond** [comment]
Next issue: https://github.com/TodePond/99/issues/1
