### ISSUE TITLE
Velocity of touch pointer is wrong

### ISSUE THREAD

**Issue by labbo-lab** [TodePond/Arroost#33]
[Screen recording 2023-04-26 12.04.22 PM.webm](https://user-images.githubusercontent.com/62490883/234650037-29cd3382-d007-4207-bd33-54ac8fe971f3.webm)

**Comment by TodePond** [comment]
Hey yeah there are quite a few issues.

biggest is probably that the pointer velocity calculations will be wrong.
we should do a special case and figure it out differently when touch events are used in https://github.com/TodePond/Arroost/blob/main/source/input/pointer.js

There's also some more issues like...
- pinch zooming doesn't work
- when you click on a tool (a tickler), it shouldn't show the weirdly placed short arrow. We should show something special and different for touch screens

**Comment by TodePond** [comment]
Currently being refactored. See #63

**Comment by TodePond** [comment]
@allcontributors add @labbo-lab for bug and usertesting

**Comment by TodePond** [comment]
@allcontributors add @labbo-lab for bug and usertesting
