### ISSUE TITLE
Upload an audio file!

### ISSUE THREAD

**Issue by TodePond** [TodePond/Arroost#47]

**Comment by TodePond** [comment]
Also mentioned in #180 ! It would be great to be able to paste, open, or drag an audio file (similar to cellpond loading)

**Comment by TodePond** [comment]
@ivanreese 👀 👀 👀

**Comment by ivanreese** [comment]
Sorry @TodePond, I'm going to have to close this as #wontfix. It goes against the improvisational spirit of Arroost. By adding an upload feature it encourages people to use Arroost in a too-considered, too-precious way. The goal is to normalise sharing scrappy fiddles. I hope you understand. But thank you for your contributions so far!

**Comment by TodePond** [comment]
haha glad you got scrappy-fiddle-pilled

you've convinced me
